name    'seteam/opencsw'
version '0.1.0'
source 'https://github.com/puppetlabs-seteam/puppet-module-opencsw'
author 'Reid Vandewiele'
license 'Apache License, Version 2.0'
summary 'Manage OpenCSW pkgutil on Solaris 10 systems'
description 'Puppet module for installing and managing OpenCSW pkgutil'
project_page 'https://github.com/puppetlabs-seteam/puppet-module-opencsw'

dependency 'nanliu/staging', '>= 0.3.1'
